#!/bin/sh

version="0.9.2"
tag=`git describe --tags --abbrev=0`
branch=`git rev-parse --abbrev-ref HEAD`
patchset="mveety"
commit=`git log -n1 --format="%h"`
versionstring="$branch-$patchset-$commit"
builddate=`date`
buildhost=`uname -n`
builduser=`whoami`
buildpath=`pwd`
buildsys=`uname`
buildarch=`uname -m`
buildstring="es $versionstring $builduser@$buildhost:$buildpath $buildsys $buildarch"

echo "#include \"es.h\""
echo "// static const char commit[] = \"$commit\";"
echo "static const char version1[] = \"$versionstring\";"
echo "static const char buildstring1[] = \"$buildstring\";"
echo "const char * const version = version1;"
echo "const char * const buildstring = buildstring1;"
echo ""
